# 调试模式开关
debug: false

# Anthropic 兼容 API 示例
api:
    type: anthropic
    url: https://api.siliconflow.cn/v1/messages
    key: YOUR_API_TOKEN
    model: deepseek-ai/DeepSeek-V3

# OpenAI 兼容 API 示例
# api:
#    type: openai
#    url: https://api.siliconflow.cn/v1/chat/completions
#    key: YOUR_API_TOKEN
#    model: deepseek-ai/DeepSeek-V3

# Ollama API 示例（同 OpenAI）
# api:
#    type: openai
#    url: http://localhost:11434/v1/chat/completions
#    key: YOUR_API_TOKEN
#    model: qwen2.5:latest

# 允许访问的环境变量
env_access:
    env_vars:
        - SHELL
        - XDG_SESSION_TYPE
        - XDG_SESSION_DESKTOP
