name: Pack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: mkdir target
      - run: bun install
      - run: bun pack
      - uses: actions/upload-artifact@v4
        with:
          name: qwq-linux-x64
          path: target/qwq-linux-x64
          compression-level: 9
      - uses: actions/upload-artifact@v4
        with:
          name: qwq-linux-arm64
          path: target/qwq-linux-arm64
          compression-level: 9
      - uses: actions/upload-artifact@v4
        with:
          name: qwq-darwin-x64
          path: target/qwq-darwin-x64.app
          compression-level: 9
      - uses: actions/upload-artifact@v4
        with:
          name: qwq-darwin-arm64
          path: target/qwq-darwin-arm64.app
          compression-level: 9
      - uses: actions/upload-artifact@v4
        with:
          name: qwq-windows-x64
          path: target/qwq-windows-x64.exe
          compression-level: 9